import { existsSync, readFileSync, readdirSync, realpathSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const compare = (a, b) => a < b ? -1 : a > b ? 1 : 0;
const readJSON = (filename) => JSON.parse(readFileSync(filename, 'utf8'));

// Resolve package directories rather than exported package.json subpaths. This also
// handles nested versions and packages that forbid package.json through exports.
function resolvePackage(name, from) {
  if (!/^(?:@[^/]+\/)?[^/]+$/.test(name) || name.includes('..')) throw new Error(`Invalid dependency name: ${name}`);
  for (let current = from; ; current = path.dirname(current)) {
    const candidate = path.join(current, 'node_modules', name);
    if (existsSync(path.join(candidate, 'package.json'))) return realpathSync(candidate);
    if (path.dirname(current) === current) return null;
  }
}

export function productionPackages(root = projectRoot) {
  const visited = new Map();
  function visit(directory, isRoot = false) {
    if (visited.has(directory)) return;
    const manifest = readJSON(path.join(directory, 'package.json'));
    if (!isRoot) visited.set(directory, { directory, manifest });
    const dependencies = new Set([
      ...Object.keys(manifest.dependencies ?? {}),
      ...Object.keys(manifest.optionalDependencies ?? {}),
      ...Object.keys(manifest.peerDependencies ?? {}),
    ]);
    for (const name of [...dependencies].sort(compare)) {
      const installed = resolvePackage(name, directory);
      if (!installed) {
        if (Object.hasOwn(manifest.optionalDependencies ?? {}, name)
          || manifest.peerDependenciesMeta?.[name]?.optional) continue;
        throw new Error(`Missing installed dependency ${name} required by ${manifest.name}`);
      }
      visit(installed);
    }
  }
  visit(realpathSync(root), true);
  return [...visited.values()].sort((a, b) => compare(
    `${a.manifest.name}@${a.manifest.version}:${path.relative(root, a.directory)}`,
    `${b.manifest.name}@${b.manifest.version}:${path.relative(root, b.directory)}`,
  ));
}

function licenseFiles(directory) {
  const files = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    if (!/^(?:licen[sc]e|copying|copyright|notice)(?:$|[._-])/i.test(entry.name)) continue;
    if (entry.isFile()) files.push(entry.name);
  }
  // Some distributions put multiple notices in these directories.
  function collect(relative) {
    for (const entry of readdirSync(path.join(directory, relative), { withFileTypes: true })) {
      const filename = path.join(relative, entry.name);
      if (entry.isDirectory()) collect(filename);
      else if (entry.isFile()) files.push(filename);
    }
  }
  for (const name of ['licenses', 'LICENSES', 'notices', 'NOTICES']) {
    if (existsSync(path.join(directory, name)) && statSync(path.join(directory, name)).isDirectory()) collect(name);
  }
  if (!files.some((name) => /^(?:licen[sc]e|copying)(?:$|[s._/-])/i.test(name))) {
    throw new Error(`Missing license text in ${directory}; add a reviewed source, never omit the package.`);
  }
  return files.sort(compare);
}

function sourceSection(label, filename) {
  const contents = readFileSync(filename);
  if (!contents.toString('utf8').trim()) throw new Error(`Empty license/notice: ${filename}`);
  // Keep the file bytes, including copyright lines and line endings, unchanged.
  return Buffer.concat([Buffer.from(`\n--- ${label} ---\n\n`), contents, Buffer.from('\n')]);
}

export function generateNotices(root = projectRoot) {
  const packages = productionPackages(root);
  const chunks = [Buffer.from(`THIRD-PARTY NOTICES — Session Dock

Generated by scripts/generate-notices.mjs from installed package contents.
Do not edit. Run npm run notices after changing dependencies.

Scope: the complete installed production dependency graph, including transitive
and installed peer/optional dependencies. This conservative list may include
code or type declarations removed by bundling. Dev-only build/test tools are
excluded. Electron is included separately because its runtime is distributed.
License identifiers are package metadata; the original texts below govern.
Original license and notice file contents are reproduced without modification.

Electron/Chromium notices also ship beside app.asar under licenses/:
  electron-LICENSE.txt
  LICENSES.chromium.html (Electron's complete Chromium and runtime notices)

Production dependency packages: ${packages.length}
`)];
  for (const { directory, manifest } of packages) {
    if (!manifest.name || !manifest.version || typeof manifest.license !== 'string'
      || !manifest.license.trim() || /^(?:UNLICENSED|UNKNOWN)$/i.test(manifest.license)) {
      throw new Error(`Missing/unsupported license identification in ${directory}/package.json`);
    }
    chunks.push(Buffer.from(`\n${'='.repeat(78)}\n${manifest.name}@${manifest.version}\nLicense: ${manifest.license}\nInstalled path: ${path.relative(root, directory).split(path.sep).join('/')}\n`));
    for (const filename of licenseFiles(directory)) {
      chunks.push(sourceSection(filename.split(path.sep).join('/'), path.join(directory, filename)));
    }
  }
  const electron = readJSON(path.join(root, 'node_modules/electron/package.json'));
  if (!electron.version || !electron.license) throw new Error('Missing Electron license identification');
  chunks.push(Buffer.from(`\n${'='.repeat(78)}\nElectron ${electron.version}\nLicense: ${electron.license}\n`));
  chunks.push(sourceSection('Electron runtime LICENSE', path.join(root, 'node_modules/electron/dist/LICENSE')));
  const chromium = path.join(root, 'node_modules/electron/dist/LICENSES.chromium.html');
  if (!existsSync(chromium) || statSync(chromium).size === 0) throw new Error('Missing Electron/Chromium runtime notices');
  for (const filename of ['dm-sans-OFL.txt', 'space-grotesk-OFL.txt']) {
    chunks.push(sourceSection(`Bundled font: ${filename}`, path.join(root, 'public/licenses', filename)));
  }
  return Buffer.concat(chunks);
}

export function noticeOutputs(root = projectRoot) {
  const thirdParty = generateNotices(root);
  const publicNotices = Buffer.concat([
    Buffer.from('SESSION DOCK — LICENSE AND ACKNOWLEDGEMENTS\n'),
    sourceSection('Session Dock LICENSE', path.join(root, 'LICENSE')),
    Buffer.from('\n'), thirdParty,
  ]);
  return new Map([['THIRD_PARTY_NOTICES.txt', thirdParty], ['public/notices.txt', publicNotices]]);
}

export function checkNotices(root = projectRoot) {
  for (const [filename, expected] of noticeOutputs(root)) {
    if (!existsSync(path.join(root, filename)) || !readFileSync(path.join(root, filename)).equals(expected)) {
      throw new Error(`Stale or missing ${filename}; run npm run notices and review the changes.`);
    }
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  if (process.argv.includes('--check')) {
    checkNotices();
    console.log('License notices match the installed production dependency graph.');
  } else {
    for (const [filename, contents] of noticeOutputs()) writeFileSync(path.join(projectRoot, filename), contents);
    console.log(`Generated license notices for ${productionPackages().length} production dependency packages, Electron, and fonts.`);
  }
}
