import type { FormEvent, ReactNode } from 'react';
import { ArrowRight, LoaderCircle, Pencil, Tag, Terminal, Trash2, X } from 'lucide-react';
import type { ConnectionStatus, Message, Session } from '../shared/types';
import ThirdPartyNotices from './ThirdPartyNotices';
import DockMark from './DockMark';
import { normalizeTags, setTags, MAX_TAGS, MAX_TAG_LENGTH, type SessionMeta } from './sessionMeta';
import { newSessionShortcut, paletteShortcut } from './platform';

export type DialogKind = 'rename' | 'delete' | 'about' | 'settings' | 'close-owned' | 'resume-owned' | 'fork-owned' | 'tags' | 'palette';

export function Modal({ dialog, dialogPending, setDialog, children }: { dialog: DialogKind; dialogPending: boolean; setDialog: (dialog: DialogKind | null) => void; children: ReactNode }) {
  return <div className="modal-backdrop" onClick={() => { if (!dialogPending) setDialog(null); }}><section className={`modal ${dialog === 'settings' ? 'settings-modal' : dialog === 'palette' ? 'palette-modal' : ''}`} role="dialog" aria-modal="true" aria-labelledby="dialog-title" onClick={event => event.stopPropagation()} onKeyDown={event => { if (event.key === 'Tab') { const elements = Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), select:not(:disabled), textarea:not(:disabled), a[href], summary')).filter(node => node.checkVisibility() && !node.closest('[inert]'));  const first = elements[0]; const last = elements[elements.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus(); } } }}><button className="modal-close icon-button" aria-label="Close dialog" onClick={() => setDialog(null)} disabled={dialogPending}><X size={18} /></button>{children}</section></div>;
}

export function TagsDialog({ active, meta, updateMeta, tagInput, setTagInput, onClose }: { active: Session; meta: SessionMeta; updateMeta: (next: SessionMeta) => void; tagInput: string; setTagInput: (value: string) => void; onClose: () => void }) {
  return <form onSubmit={event => { event.preventDefault(); updateMeta(setTags(meta, active.id, normalizeTags(tagInput))); onClose(); }}><div className="modal-icon"><Tag size={22} /></div><h2 id="dialog-title">Edit tags</h2><p>Tags are kept only in this app to help you find sessions. Separate them with commas (up to {MAX_TAGS}, {MAX_TAG_LENGTH} characters each).</p><input className="rename-input" aria-label="Tags" value={tagInput} onChange={event => setTagInput(event.target.value)} autoFocus placeholder="bug, refactor, urgent" /><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => onClose()}>Cancel</button><button type="submit" className="primary-button">Save tags</button></div></form>;
}

export function AboutDialog({ connection, onClose }: { connection: ConnectionStatus | null; onClose: () => void }) {
  return <><div className="about-logo"><DockMark />Session Dock</div><h2 id="dialog-title">Your agent. At home on your desktop.</h2><p>Session Dock is an unofficial companion for Prime Agent CLI. It is not affiliated with or endorsed by Prime Intellect.</p><p>Your sessions and tools run on your machine using your existing CLI configuration. Prime Agent is a separate project and must be installed independently.</p><div className="about-detail"><Terminal size={15} />{connection?.version ? `Prime Agent ${connection.version}` : 'Prime Agent CLI'}<span>{connection?.connected ? 'Connected' : 'Disconnected'}</span></div><ThirdPartyNotices /><p className="about-shortcut">New session <kbd>{newSessionShortcut}</kbd><br />Command palette <kbd>{paletteShortcut}</kbd><br />Send a message <kbd>Enter</kbd><br />Insert a new line <kbd>Shift + Enter</kbd></p><button className="primary-button" autoFocus onClick={() => onClose()}>Let’s build<ArrowRight size={15} /></button></>;
}

export function HistoryDialog({ dialog, active, messages, error, forkEntryId, setForkEntryId, historyConsent, setHistoryConsent, dialogPending, confirmHistory, onClose }: { dialog: 'resume-owned' | 'fork-owned'; active: Session | undefined; messages: Message[]; error: string; forkEntryId: string; setForkEntryId: (id: string) => void; historyConsent: boolean; setHistoryConsent: (consent: boolean) => void; dialogPending: boolean; confirmHistory: (event: FormEvent) => Promise<void>; onClose: () => void }) {
  return <form onSubmit={confirmHistory}><h2 id="dialog-title">{dialog === 'resume-owned' ? 'Resume saved session?' : 'Fork saved session?'}</h2><p>{dialog === 'resume-owned' ? 'Reopen this saved desktop conversation in its original workspace. No prompt is sent until you choose to send one.' : 'Create a separate desktop conversation from this saved history, in the same workspace. The original stays closed. No prompt is sent automatically.'}</p>{dialog === 'fork-owned' && <label>History to copy<select aria-label="Fork through message" disabled={dialogPending} value={forkEntryId} onChange={event => setForkEntryId(event.target.value)}><option value="">Full saved history</option>{messages.filter(message => message.role === 'user' || message.role === 'assistant').map(message => <option key={message.id} value={message.id}>{message.role}: {message.content.slice(0, 100) || 'Image message'}</option>)}</select><p>The selected message is included. Later messages are excluded. Messages containing tool calls cannot be selected.</p></label>}<label className="workspace-consent"><input type="checkbox" checked={historyConsent} disabled={dialogPending} onChange={event => setHistoryConsent(event.target.checked)} />I trust this workspace. Prime may run tools and change files with my user permissions. This is not a sandbox.</label>{error && <p role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="secondary-button" disabled={dialogPending} onClick={() => onClose()}>Cancel</button><button type="submit" className="primary-button" disabled={dialogPending || !historyConsent || active?.lifecycle !== 'closed'}>{dialogPending && <LoaderCircle className="spin" size={14} />}{dialog === 'resume-owned' ? 'Resume session' : 'Create fork'}</button></div></form>;
}

export function CloseOwnedDialog({ dialogPending, confirmDialog, onClose }: { dialogPending: boolean; confirmDialog: (event: FormEvent) => Promise<void>; onClose: () => void }) {
  return <form onSubmit={confirmDialog}><h2 id="dialog-title">Close desktop session?</h2><p>This stops its owned agent process and queued work. Saved history stays available. You can explicitly resume or fork it later after confirming workspace trust. Shared CLI sessions and independently created agents are not stopped.</p><div className="modal-actions"><button type="button" className="secondary-button" disabled={dialogPending} onClick={() => onClose()}>Cancel</button><button type="submit" className="danger-button" disabled={dialogPending}>Close and stop</button></div></form>;
}

export function RenameDeleteDialog({ dialog, active, renameTitle, setRenameTitle, dialogPending, confirmDialog, onClose }: { dialog: DialogKind; active: Session | undefined; renameTitle: string; setRenameTitle: (title: string) => void; dialogPending: boolean; confirmDialog: (event: FormEvent) => Promise<void>; onClose: () => void }) {
  return <form onSubmit={confirmDialog}><div className={`modal-icon ${dialog === 'delete' ? 'destructive' : ''}`}>{dialog === 'delete' ? <Trash2 size={22} /> : <Pencil size={22} />}</div><h2 id="dialog-title">{dialog === 'delete' ? 'Delete this session?' : 'Rename session'}</h2><p>{dialog === 'delete' ? `“${active?.title || 'This session'}” will be permanently deleted from your shared CLI history. Its active worker will be stopped. This cannot be undone.` : 'Give this conversation a name that’s easy to find.'}</p>{dialog === 'rename' && <input className="rename-input" aria-label="Session title" value={renameTitle} onChange={event => setRenameTitle(event.target.value)} autoFocus maxLength={200} required />}<div className="modal-actions"><button type="button" className="secondary-button" autoFocus={dialog === 'delete'} onClick={() => onClose()} disabled={dialogPending}>Cancel</button><button type="submit" className={dialog === 'delete' ? 'danger-button' : 'primary-button'} disabled={dialogPending || (dialog === 'rename' && !renameTitle.trim())}>{dialogPending && <LoaderCircle className="spin" size={14} />}{dialog === 'delete' ? 'Delete session' : 'Save name'}</button></div></form>;
}
